### ISSUE TITLE
RedirectRequiredException running CalendarTest sample

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gdata-java-client#123]
```
What steps will reproduce the problem?
1. Install gdata (and prereqs) for Java
2. Run sample calendar test found at
http://code.google.com/apis/gdata/articles/java_client_lib.html#helloworld
3.

What is the expected output? What do you see instead?
Expect a list of Calendar names.  Get an exception of the form:

Exception in thread "main" com.google.gdata.util.RedirectRequiredException:
Moved Temporarily
<HTML>
<HEAD>
<TITLE>Moved Temporarily</TITLE>
</HEAD>
<BODY BGCOLOR="#FFFFFF" TEXT="#000000">
<H1>Moved Temporarily</H1>
The document has moved <A
HREF="http://www.google.com/calendar/feeds/default/allcalendars/full?gsessionid=
xxxxsessionidxxxx">here</A>.
</BODY>
</HTML>

    at
com.google.gdata.client.http.GoogleGDataRequest.handleErrorResponse(GoogleGDataR
equest.java:560)
    at
com.google.gdata.client.http.HttpGDataRequest.checkResponse(HttpGDataRequest.jav
a:481)
    at
com.google.gdata.client.http.HttpGDataRequest.execute(HttpGDataRequest.java:460)
    at
com.google.gdata.client.http.GoogleGDataRequest.execute(GoogleGDataRequest.java:
534)
    at com.google.gdata.client.Service.getFeed(Service.java:962)
    at com.google.gdata.client.Service.getFeed(Service.java:819)
    at com.google.gdata.client.GoogleService.getFeed(GoogleService.java:600)
    at com.google.gdata.client.Service.getFeed(Service.java:838)
    at CalTest.main(CalTest.java:23)


What version of the product are you using? On what operating system?
GData v1.30.0
Mac OS X 10.5.6

Please provide any additional information below.
While it is true that the example mentions it has no exception handling it
is a bit of an obstacle for first-timers to have to hunt down how to deal
with a redirect.  Other than this wart, the getting started section got me
up and running very smoothly.  Something like the following worked for me:

    public static void main(String[] args) throws IOException, ServiceException
    {
        CalendarService cs = new CalendarService("sample");
        cs.setUserCredentials("username@gmail.com", "password");

        URL feedUrl = new
URL("http://google.com/calendar/feeds/default/allcalendars/full");

        CalendarFeed feed = null;
        try
        {
            feed = cs.getFeed(feedUrl, CalendarFeed.class);
        }
        catch (RedirectRequiredException re)
        {
            feedUrl = new URL(re.getRedirectLocation());
            feed = cs.getFeed(feedUrl, CalendarFeed.class);
        }

        for (CalendarEntry entry : feed.getEntries())
        {
            System.out.println(entry.getTitle().getPlainText());
        }
    }



```

Original issue reported on code.google.com by `michael....@gmail.com` on 13 Apr 2009 at 2:49

**Comment by er1c** [comment]
I'm now getting a similar error:

    fm.util.GoogleDocs  -  Calling GoogleDocs API...
    fm.util.GoogleDocs  -  Google Docs Export: https://spreadsheets.google.com/feeds/download/spreadsheets/Export?key=0Ai7IYcrzwmCMdFloak50NGN5cmZlWkVqbXRYMmR2aXc&gid=0&exportFormat=tsv
    fm.util.GoogleDocs  -  Caught unhandled exception: com.google.gdata.util.RedirectRequiredException: Moved Temporarily
    <HTML>
    <HEAD>
    <TITLE>Moved Temporarily</TITLE>
    </HEAD>
    <BODY BGCOLOR="#FFFFFF" TEXT="#000000">
    <H1>Moved Temporarily</H1>
    The document has moved <A HREF="https://docs.google.com/a/frugalmechanic.com/spreadsheets/d/1HJ-wP0oEPMP9Kz1f17wOabbfXhsqkgk0hHGoBEVmrX8/export?gid=0&amp;exportFormat=tsv">here</A>.
    </BODY>
    </HTML>

If I try/catch the RedirectRequiredException I get a cookie error:

    fm.util.GoogleDocs  -  Calling GoogleDocs API...
    fm.util.GoogleDocs  -  Google Docs Export: https://spreadsheets.google.com/feeds/download/spreadsheets/Export?key=0Ai7IYcrzwmCMdFloak50NGN5cmZlWkVqbXRYMmR2aXc&gid=0&exportFormat=tsv
    fm.util.GoogleDocs  -  Google Docs Export: https://docs.google.com/a/frugalmechanic.com/spreadsheets/d/1HJ-wP0oEPMP9Kz1f17wOabbfXhsqkgk0hHGoBEVmrX8/export?gid=0&exportFormat=tsv
    fm.util.GoogleDocs  -  Caught unhandled exception: java.lang.IllegalArgumentException: Trying to set foreign cookie
    fm.util.GoogleDocs  -  Retrying: Calling GoogleDocs API


    def makeRequest(url: URL): String = {
      val request = service.createEntryRequest(url)

      try {
        logger.info("Google Docs Export: "+url)
        request.execute()
        InputStreamResource(request.getResponseStream()).readToString("UTF-8")
      } catch {
        case e: com.google.gdata.util.RedirectRequiredException => makeRequest(new URL(e.getRedirectLocation))
      } finally {
        request.end()
      }
    }


Thoughts?
