### ISSUE TITLE
Gdata Java Contact API : "No authentication header information" when adding a parameter to a Query using 2-legged OAuth

### ISSUE THREAD

**Issue by GoogleCodeExporter** [google/gdata-java-client#257]
```
Here is my simple code:

// Setup Oauth
GoogleOAuthParameters oauthParam = new GoogleOAuthParameters();
oauthParam.setOAuthConsumerKey(oAuthConsumerKey);
oauthParam.setOAuthConsumerSecret(oAuthConsumerSecret);
oauthParam.setOAuthType(OAuthType.TWO_LEGGED_OAUTH);

// set the feedURL (googleAccount = you@yourdomain.com)
contactsFeedUrl = new URL(METAFEED_URL_CONTACTS + "?xoauth_requestor_id=" +
this.googleAccount);

// Init the service and set the auth
contactsService = new ContactsService("myerp.com");
contactsService.setOAuthCredentials(oauthParam, new OAuthHmacSha1Signer());

// The query that will retrieve all contacts
Query myQuery = new Query(contactsFeedUrl);

// Execute the request
ContactFeed resultFeed = contactsService.getFeed(myQuery, ContactFeed.class);

-----------------

The code above works. But if I add before executing the request

myQuery.setMaxResults(MAX_RESULT);

it fails with 

java.lang.NullPointerException: No authentication header information 
at
com.google.gdata.util.AuthenticationException.initFromAuthHeader(AuthenticationE
xception.java:96)
at
com.google.gdata.util.AuthenticationException.<init>(AuthenticationException.jav
a:67)
at
com.google.gdata.client.http.HttpGDataRequest.handleErrorResponse(HttpGDataReque
st.java:596)
at
com.google.gdata.client.http.GoogleGDataRequest.handleErrorResponse(GoogleGDataR
equest.java:563)



I'm using gdata 1.41.1, java 6
```

Original issue reported on code.google.com by `thomas.r...@gmail.com` on 11 Apr 2010 at 2:46
- Merged into: #263

**Comment by gurmeetsingh90** [comment]
Have any one resolved this issue.
I'm getting same issue?
java.lang.NullPointerException: No authentication header information

 private void setOauthParameter() {
        GoogleOAuthParameters oauthParam = new GoogleOAuthParameters();
        oauthParam.setOAuthConsumerKey(ClientId);
        oauthParam.setOAuthConsumerSecret(ClientSecrate);
        oauthParam.setOAuthType(OAuthParameters.OAuthType.TWO_LEGGED_OAUTH);

        // Init the service and set the auth
        service = new ContactsService("chat.com.contactssharing");
        try {
            service.setOAuthCredentials(oauthParam, new OAuthHmacSha1Signer());

            service.getRequestFactory().setHeader("User-Agent", "chat.com.contactssharing");

        } catch (OAuthException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }

    }

when i'm getting Query parameter i'm getting this issue Query myQuery = new Query(feedUrl);
        myQuery.setMaxResults(50);
        myQuery.setStartIndex(1);
        //  myQuery.setStringCustomParameter("showdeleted", "false");
        //   myQuery.setStringCustomParameter("requirealldeleted", "false");
        //        myQuery.setStringCustomParameter("sortorder", "ascending");
        //        myQuery.setStringCustomParameter("orderby", "");


        try {
            **

> ContactFeed resultFeed = (ContactFeed) this.service.query(myQuery, ContactFeed.class);

**
            Log.d(TAG, resultFeed.toString());
            for (ContactEntry entry : resultFeed.getEntries()) {
                printContact(entry);
            }
            System.err.println("Total: " + resultFeed.getEntries().size() + " entries found");

        } **

> catch (Exception ex) {
>             System.err.println("Not all placehorders of deleted entries are available");
>         }

**
