### ISSUE TITLE
How to use Google OAuth2 in place of picasaService.setUserCredentials()?

### ISSUE THREAD

**Issue by derrenbrown** [google/gdata-java-client#452]
Hi,

I have been searching high and low for a solution/workaround for this but haven't found anything useful.

My Java application had been uploading photos to Picasa Web albums. It used setUserCredentials() for authentication. It had been working fine for years until recently. It seems the support for setUserCredentials has stopped.

How can I use the OAuth2 with the gdata library - especially the Picasa API? There's no replacement API for Picasa. Thanks very much!

**Comment by ejona86** [comment]
Yes, setUserCredentials used ClientLogin, which has been deprecated for a while and is now disabled.

You can call setOAuth2Credentials instead. See https://developers.google.com/api-client-library/java/google-oauth-java-client/oauth2 for documentation of getting a Credential.
